Repository microsoft/DeepSpeed, pull requests merged in 2020-02, with the labels that each got.

#51 Moving to major/minor/patch versioning.
  deepspeed/__init__.py
  install.sh
  setup.py
  tests/unit/test_config.py
Labels: enhancement

#52 Porting JSON config documentation
  README.md
  docs/config_json.md
Labels: documentation

#49 Changing README headers and testing discussion
  README.md
Labels: documentation

#53 Doc edits, typos, etc.
  CONTRIBUTING.md
  Dockerfile
  README.md
  docs/azure.md
  docs/features.md
  docs/tutorials/CIFAR-10.md
  docs/tutorials/MegatronGPT2Tutorial.md
Labels: documentation

#54 Publication section in ToC
  README.md
Labels: documentation

#47 Ported 1Cycle tutorial.
  README.md
  docs/figures/1cycle_lr.png
  docs/figures/lr_schedule.png
  docs/figures/model_convergence.png
  docs/tutorials/1Cycle.md
Labels: documentation

#45 LRRT tutorial
  README.md
  docs/features.md
  docs/figures/loss_and_lr.png
  docs/tutorials/lrrt.md
Labels: documentation

#69 Fix broken links in CIFAR
  docs/tutorials/CIFAR-10.md
Labels: bug, documentation

#72 fix typo
  README.md
Labels: documentation

#79 Add requirements for cifar10
  docs/tutorials/CIFAR-10.md
  requirements.txt
Labels: documentation

#92 Updating model parallelism docs
  deepspeed/__init__.py
  docs/features.md
Labels: documentation

#103 Update stale links from old website transition.
  README.md
Labels: documentation
