Repository microsoft/DeepSpeed, pull requests merged in 2020-10, with the labels that each got.

#458 Do not load optimizer states for fp32 if flag set to False
  deepspeed/runtime/engine.py
Labels: bug

#460 fixing transformer tutorial
  docs/_tutorials/transformer_kernel.md
Labels: documentation

#475 updates website dependencies
  docs/Gemfile.lock
  docs/index.md
Labels: bug, website
