Repository microsoft/DeepSpeed, pull requests merged in 2020-09, with the labels that each got.

#351 Jekyll installation instructions
  docs/Gemfile.lock
  docs/README.md
Labels: documentation, website

#368 Move code quality tests to Azure-hosted agents.
  azure-pipelines.yml
Labels: build

#392 Pipeline parallel training engine.
  deepspeed/__init__.py
  deepspeed/pipe/__init__.py
  deepspeed/runtime/activation_checkpointing/checkpointing.py
  deepspeed/runtime/config.py
  deepspeed/runtime/dataloader.py
  deepspeed/runtime/engine.py
  deepspeed/runtime/fp16/fused_optimizer.py
  deepspeed/runtime/fp16/unfused_optimizer.py
  deepspeed/runtime/pipe/__init__.py
  deepspeed/runtime/pipe/engine.py
  deepspeed/runtime/pipe/module.py
  deepspeed/runtime/pipe/p2p.py
  deepspeed/runtime/pipe/schedule.py
  deepspeed/runtime/pipe/topology.py
  deepspeed/runtime/utils.py
  deepspeed/runtime/zero/stage1.py
  deepspeed/utils/__init__.py
  deepspeed/utils/timer.py
  docs/_data/navigation.yml
  docs/_tutorials/pipeline.md
  docs/assets/images/3d-parallelism.png
  docs/assets/images/pipe-schedule.png
  docs/code-docs/source/conf.py
  docs/code-docs/source/index.rst
  docs/code-docs/source/pipeline-extending.rst
  docs/code-docs/source/pipeline.rst
  install.sh
  tests/unit/common.py
  tests/unit/simple_model.py
  tests/unit/test_checkpointing.py
  tests/unit/test_data.py
  tests/unit/test_partition.py
  tests/unit/test_pipe.py
  tests/unit/test_pipe_module.py
  tests/unit/test_pipe_schedule.py
  tests/unit/test_runtime_utils.py
  tests/unit/test_topology.py
Labels: documentation, enhancement, website

#402 readthedocs upgrade
  .gitignore
  deepspeed/runtime/engine.py
  deepspeed/runtime/pipe/engine.py
  deepspeed/runtime/pipe/module.py
  docs/code-docs/source/conf.py
  docs/code-docs/source/deepspeed.pt.rst
  docs/code-docs/source/deepspeed.rst
  docs/code-docs/source/index.rst
  docs/code-docs/source/model-checkpointing.rst
  docs/code-docs/source/modules.rst
  docs/code-docs/source/pipeline-extending.rst
  docs/code-docs/source/pipeline.rst
  docs/code-docs/source/training.rst
Labels: documentation, website

#408 Scales pipeline throughput by logging frequency
  deepspeed/runtime/pipe/engine.py
Labels: bug

#318 Fix zero-1 bug related to stitching reduced grads across comm partitions
  deepspeed/runtime/zero/stage1.py
Labels: bug

#414 Linear warmup+decay lr schedule
  deepspeed/runtime/lr_schedules.py
  tests/unit/test_lr_schedulers.py
Labels: enhancement

#416 Overflow fix
  deepspeed/runtime/fp16/fused_optimizer.py
Labels: bug

#410 readthedocs yaml configuration
  .gitignore
  .readthedocs.yml
  deepspeed/git_version_info.py
  docs/_tutorials/pipeline.md
  docs/code-docs/requirements.local.txt
  docs/code-docs/source/conf.py
  docs/code-docs/source/deepspeed.rst
  docs/code-docs/source/training.rst
  install.sh
  requirements/requirements-dev.txt
  requirements/requirements-readthedocs.txt
  setup.py
Labels: dependencies, documentation, website

#421 Fix activation checkpoint unit tests for GPU systems
  deepspeed/runtime/activation_checkpointing/checkpointing.py
  tests/unit/test_activation_checkpointing.py
Labels: bug

#441 Link fix part 2
  docs/_tutorials/pipeline.md
Labels: website

#442 unit test rename
  tests/unit/test_cpu_adam.py
Labels: build
